export const EmailRegex = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;

export const StackList = {
  language: [
    "JavaScript",
    "HTML/CSS",
    "SQL",
    "Python",
    "Java",
    "Bash/Shell",
    "C#",
    "PHP",
    "TypeScript",
    "C++",
    "C",
    "Go",
    "Kotlin",
    "Ruby",
    "VBA",
    "Swift",
    "R",
    "Rust",
    "Objective-C",
    "Dart",
    "Scala",
    "Perl",
    "Haskell",
    "julia",
  ],
  framework: [
    "JQuery",
    "React.js",
    "Angular.js",
    "ASP.NET",
    "Express",
    "Vue.js",
    "Spring",
    "Django",
    "Flask",
    "Laravel",
    "Ruby on Rails",
    "Gatsby",
    "Node.js",
    ".NET",
    "React Native",
    "Unity 3D",
    "Android",
    "Flutter",
    "Cordorva",
    "Xamarin",
    "Unreal Engine",
  ],
  database: [
    "MySQL",
    "PostgreSQL",
    "Microsoft SQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "MariaDB",
    "Oracle",
    "Firebase",
    "Elasticsearch",
    "DynamoDB",
    "Cassandra",
    "IBM DB2",
  ],
  cloudos: [
    "Linux",
    "Docker",
    "AWS",
    "Raspberry Pi",
    "Azure",
    "WordPress",
    "Kubernetes",
    "Heroku",
    "Arduino",
  ],
  mldl: ["Pandas", "TensorFlow", "Keras", "Torch/PyThoch", "Hadoop", "Spark"],
};
