export const SERVER_URL = "http://localhost:4000";

export const EmailRegex = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;

export const Locations = [
  { key: "02", value: "서울" },
  { key: "031", value: "경기" },
  { key: "032", value: "인천" },
  { key: "033", value: "강원" },
  { key: "041", value: "충남" },
  { key: "042", value: "대전" },
  { key: "043", value: "충북" },
  { key: "051", value: "부산" },
  { key: "052", value: "울산" },
  { key: "053", value: "대구" },
  { key: "054", value: "경북" },
  { key: "055", value: "경남" },
  { key: "061", value: "전남" },
  { key: "062", value: "광주" },
  { key: "063", value: "전북" },
  { key: "064", value: "제주" },
];

export const StackList = {
  language: [
    "JavaScript",
    "HTML/CSS",
    "SQL",
    "Python",
    "Java",
    "Bash/Shell",
    "C#",
    "PHP",
    "TypeScript",
    "C++",
    "C",
    "Go",
    "Kotlin",
    "Ruby",
    "VBA",
    "Swift",
    "R",
    "Rust",
    "Objective-C",
    "Dart",
    "Scala",
    "Perl",
    "Haskell",
    "julia",
  ],
  framework: [
    "JQuery",
    "React.js",
    "Angular.js",
    "ASP.NET",
    "Express",
    "Vue.js",
    "Spring",
    "Django",
    "Flask",
    "Laravel",
    "Ruby on Rails",
    "Gatsby",
    "Node.js",
    ".NET",
    "React Native",
    "Unity 3D",
    "Android",
    "Flutter",
    "Cordorva",
    "Xamarin",
    "Unreal Engine",
  ],
  database: [
    "MySQL",
    "PostgreSQL",
    "Microsoft SQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "MariaDB",
    "Oracle",
    "Firebase",
    "Elasticsearch",
    "DynamoDB",
    "Cassandra",
    "IBM DB2",
  ],
  cloudos: [
    "Linux",
    "Docker",
    "AWS",
    "Raspberry Pi",
    "Azure",
    "WordPress",
    "Kubernetes",
    "Heroku",
    "Arduino",
  ],
  mldl: ["Pandas", "TensorFlow", "Keras", "Torch/PyThoch", "Hadoop", "Spark"],
};
